config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :parties do
    get "timeline", on: :member #/parties/123/timeline
    resources :tasks, except: [:index]
  end

  get 'about' => 'welcome#about'
  get 'welcome' => 'welcome#welcome'

  root to: 'welcome#index'

end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :party
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :parties, dependent: :destroy
  has_many :tasks
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected

  def after_sign_in_path_for(resource)   
    welcome_path(resource)
  end
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def new
    @party = Party.new
  end

  def create
    @party = current_user.parties.build(party_params)
     if @party.save
       flash[:notice] = "Your party was created."
       redirect_to @party
     else
       flash[:error] = "There was an error. Please try again."
       render :new
     end
  end  

  def edit
    @party = Party.find(params[:id])
  end  

  def update
    @party = Party.find(params[:id])
   if @party.update_attributes(party_params)
     flash[:notice] = "Your party has been updated."
     redirect_to @party
   else
     flash[:error] = "There was an error. Please try again."
     render :edit
   end
  end

  def destroy
    @party = Party.find(params[:id])
    if @party.destroy
     flash[:notice] = "Party was deleted."
     redirect_to welcome_path
   else
     flash[:error] = "There was an error. Please try again."
     redirect_to :back
   end
  end

  def show
    @party = Party.find(params[:id])
  end

  def timeline
    @party = Party.find(params[:id])
  end

  def party_params
    params.require(:party).permit(:name, :date)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
   @party = Party.find(params[:party_id])
   @task = Task.new
  end

  def create
    @party = Party.find(params[:party_id])
    @task = @party.tasks

    @task = current_user.tasks.build(task_params )
    @task.party = @party
    @new_task = Task.new

     if @task.save
       flash[:notice] = "Your task was created."
       redirect_to timeline_party_path(@party)
     else
       flash[:error] = "There was an error. Please try again."
       render :new
     end
  end 

  def edit
    @party = Party.find(params[:party_id])
    @task = Task.find(params[:id])
  end  

  def update
    @party = Party.find(params[:party_id])
    @task = Task.find(params[:id])
   if @task.update_attributes(task_params)
     flash[:notice] = "Your task has been updated."
     redirect_to timeline_party_path(@party)
   else
     flash[:error] = "There was an error. Please try again."
     render :edit
   end
  end

  def destroy
    @party = Party.find(params[:party_id])
    @task = Task.find(params[:id])
   if @task.destroy
     flash[:notice] = "Task deleted."
     redirect_to timeline_party_path(@party)
   else
     flash[:error] = "There was an error. Please try again."
     redirect_to :back
   end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :category, :duration, :start_time, :end_time)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PartyTable</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="container">

    <ul class="nav nav-tabs">
      <% if current_user %>
        <li><%= link_to "Home", welcome_path %></li>
        <li><%= link_to "Dashboard", "#" %></li>
        <li><%= link_to "My Account", "#" %></li>
      <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      <% end %>

          <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>

    </ul>

     
   <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
   <% elsif flash[:error] %>
     <div class="alert alert-danger">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:error] %>
     </div>
   <% elsif flash[:alert] %>
     <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
     </div>
   <% end %>

<%= yield %>

<!--   <ul class="footer">
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", "#" %></li>
  </ul> -->

  </div>

</body>
</html>

app/views/parties/_calendar.html.erb
<% if @party.date %>
<center>
<script language="javascript" type="text/javascript">
//http://www.htmlbestcodes.com/Calendar.htm
var day_of_week = new Array('Sun','Mon','Tue','Wed','Thu','Fri','Sat');
var month_of_year = new Array('January','February','March','April','May','June','July','August','September','October','November','December');

//  DECLARE AND INITIALIZE VARIABLES
var Calendar = new Date();

var year = Calendar.getFullYear();     // Returns year
var month = Calendar.getMonth();    // Returns month (0-11)
var today = Calendar.getDate();    // Returns day (1-31)
var weekday = Calendar.getDay();    // Returns day (1-31)

var DAYS_OF_WEEK = 7;    // "constant" for number of days in a week
var DAYS_OF_MONTH = 31;    // "constant" for number of days in a month
var cal;    // Used for printing

Calendar.setDate(1);    // Start the calendar day at '1'
Calendar.setMonth(month);    // Start the calendar month at now


/* VARIABLES FOR FORMATTING
NOTE: You can format the 'BORDER', 'BGCOLOR', 'CELLPADDING', 'BORDERCOLOR'
      tags to customize your caledanr's look. */

var TR_start = '<TR>';
var TR_end = '</TR>';
var highlight_start = '<TD WIDTH="30"><TABLE CELLSPACING=0 BORDER=1 BGCOLOR=DEDEFF BORDERCOLOR=CCCCCC><TR><TD WIDTH=20><B><CENTER>';
var highlight_end   = '</CENTER></TD></TR></TABLE></B>';
var TD_start = '<TD WIDTH="30"><CENTER>';
var TD_end = '</CENTER></TD>';

/* BEGIN CODE FOR CALENDAR
NOTE: You can format the 'BORDER', 'BGCOLOR', 'CELLPADDING', 'BORDERCOLOR'
tags to customize your calendar's look.*/

cal =  '<TABLE BORDER=1 CELLSPACING=0 CELLPADDING=0 BORDERCOLOR=BBBBBB><TR><TD>';
cal += '<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=2>' + TR_start;
cal += '<TD COLSPAN="' + DAYS_OF_WEEK + '" BGCOLOR="#EFEFEF"><CENTER><B>';
cal += month_of_year[month]  + '   ' + year + '</B>' + TD_end + TR_end;
cal += TR_start;

//   DO NOT EDIT BELOW THIS POINT  //

// LOOPS FOR EACH DAY OF WEEK
for(index=0; index < DAYS_OF_WEEK; index++)
{

// BOLD TODAY'S DAY OF WEEK
if(weekday == index)
cal += TD_start + '<B>' + day_of_week[index] + '</B>' + TD_end;

// PRINTS DAY
else
cal += TD_start + day_of_week[index] + TD_end;
}

cal += TD_end + TR_end;
cal += TR_start;

// FILL IN BLANK GAPS UNTIL TODAY'S DAY
for(index=0; index < Calendar.getDay(); index++)
cal += TD_start + '  ' + TD_end;

// LOOPS FOR EACH DAY IN CALENDAR
for(index=0; index < DAYS_OF_MONTH; index++)
{
if( Calendar.getDate() > index )
{
  // RETURNS THE NEXT DAY TO PRINT
  week_day =Calendar.getDay();

  // START NEW ROW FOR FIRST DAY OF WEEK
  if(week_day == 0)
  cal += TR_start;

  if(week_day != DAYS_OF_WEEK)
  {

  // SET VARIABLE INSIDE LOOP FOR INCREMENTING PURPOSES
  var day  = Calendar.getDate();

  // HIGHLIGHT TODAY'S DATE
  if( today==Calendar.getDate() )
  cal += highlight_start + day + highlight_end + TD_end;

  // PRINTS DAY
  else
  cal += TD_start + day + TD_end;
  }

  // END ROW FOR LAST DAY OF WEEK
  if(week_day == DAYS_OF_WEEK)
  cal += TR_end;
  }

  // INCREMENTS UNTIL END OF THE MONTH
  Calendar.setDate(Calendar.getDate()+1);

}// end for loop

cal += '</TD></TR></TABLE></TABLE>';

//  PRINT CALENDAR
var place = document.getElementsByClassName('calendar')[0];
place.innerHTML += cal;
</script>
</center>
<% end %>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.date_select :date, order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' } %>
      <% f.submit %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', placeholder: "Give your party a name" %>
  </div>

  <div class="form-group">
    <%= f.submit "Let's Go", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/parties/_planner_grid.html.erb
<table>  
  <tbody>
    <tr>
      <th rowspan='2' class='timelable'>11:00 AM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>12:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>  
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>1:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>2:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>  
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>3:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>4:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>  
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>5:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>  
    </tr>
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>6:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td> 
    </tr>
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>7:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>8:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable'>9:00 PM</td>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>  
    <tr>
      <td class='prep x'></td>
      <td class='oven x'></td>
      <td class='stove x'></td>
      <td class='grill x'></td>
    </tr>
    <tr>
      <th rowspan='2' class='timelable stationlable'></td>
      <td class='prep stationlable'>Prep</th>
      <td class='oven stationlable'>Oven</th>
      <td class='stove stationlable'>Stove</th>
      <td class='grill stationlable'>Grill</th>
    </tr>  
  </tbody>
</table>

app/views/parties/edit.html.erb
<%= render 'form' %>

app/views/parties/new.html.erb
<h3>Let's Start Planning!</h3>

<%= render 'form' %>

app/views/parties/show.html.erb
<div class='white-box'>
  <div class='pull-right'><h5>
    Party Date: <%= @party.date.strftime('%a. %B %d, %Y') %><br>
    Party Time: <%= @party.date.strftime('%I:%M %p') %><br>
    Guest Count:
  </h5></div> 

  <h2 class='header'><%= @party.name %></h2>
    <h3>Dashboard</h3>
  <br>
  <div class='row party'>
    <div class='col-md-2 guest'>
      <p>Guest List</p>
    </div>
    <div class='col-md-2 menu'>
      <p>Menu and Contribution List</p>
    </div>
    <div class='col-md-2 grocery'>
      <p>Grocery List</p>
    </div>
    <div class='col-md-2 table-decor'>
      <p>Tableware and Decorations</p>
    </div>
    <div class='col-md-2 timeline'>
      <p><%= link_to 'Timeline Planner', timeline_party_path(@party) %></p>
    </div>
  </div>
</div>

app/views/parties/timeline.html.erb
<h1 class='text-center'><%= @party.name %></h1>

<div class='col-md-4'>
  <div class='task-list'>
    <div>
  <!--     calendar here -->  
    </div>

    <div>
      <h4 class='text-center'>To Do List</h4>
      <ul>
        <li>Grocery List</li>
            <% @party.tasks.each do |task| %>
              <ul> 
                <% if task.category == 'Grocery List' %>
                  <%= render partial: 'tasks/task', locals: { task: task } %>
                  <% end %>
              </ul>
            <% end %>        
          <li>Food Prep and Cooking</li>
            <% @party.tasks.each do |task| %>
              <ul> 
                <% if task.category == 'Food Prep and Cooking' %>
                  <%= render partial: 'tasks/task', locals: { task: task } %>
                <% end %>
              </ul>
            <% end %>
          <li>Tableware and Decor Set-up</li>
            <% @party.tasks.each do |task| %>
              <ul> 
                <% if task.category == 'Tableware and Decor Set-up' %>
                  <%= render partial: 'tasks/task', locals: { task: task } %>
                <% end %>
              </ul>
            <% end %>
       </ul>
       <p id='add-task'><%= link_to '+ Add Item', new_party_task_path(@party) %></p> 
    </div>
  </div>
</div>

<div class='col-md-8'>
  <div class='timeline-planner'>
    <div class='blue-date-box'>
      <h4 class='text-center'><%= @party.date.strftime('%A %B %d %Y') %></h4> 
    </div>
    <!--     timeline planner goes here --> 
    <%= render 'planner_grid' %> 
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for [@party, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :task_name %><br>
    <%= f.text_field :title, class: 'form-control medium' %>
  </div>
  <div class="form-group">
    <%= f.label :category %><br>  
    <%= f.radio_button :category, "Grocery List" %>
    <%= f.label :category_grocery, "Grocery List" %><br>
    <%= f.radio_button :category, "Food Prep and Cooking" %>
    <%= f.label :category_food, "Food Prep and Cooking" %><br>
    <%= f.radio_button :category, "Tableware and Decor Set-up" %>
    <%= f.label :category_tableware, "Tableware and Decor Set-up" %>
  </div>
  <div class="form-group">
    <%= f.label :how_long_will_it_take? %><br>
    <span class="inline"><%= f.number_field :duration, min: 1, class: 'form-control short' %></span><span class="inline">&nbsp minutes</span>
  </div>  
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control medium', placeholder: "Add additional details here" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %> 

app/views/tasks/_task.html.erb
<li>
  <span class='draggable'><%= task.title %></span>,
  <%= task.duration %> minutes 
  <%= link_to edit_party_task_path(task.party, task) do %><i class="glyphicon glyphicon-pencil"></i><% end %>
  <%= link_to [task.party, task], method: :delete, data: { confirm: "Delete this task?"  } do %><i class="glyphicon glyphicon-remove"></i><% end %>
</li>

app/views/tasks/edit.html.erb
<h3>Edit Task</h3>

<%= render 'form' %>

app/views/tasks/new.html.erb
<h3>New Task</h3>

<%= form_for [@party, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :task_title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.text_field :category, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :estimated_duration %><br>
    <%= f.text_field :duration, class: 'form-control', placeholder: "How long will it take?" %>
  </div>  
  <div class="form-group">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time, class: 'form-control', placeholder: "When will you start this task?" %>
  </div>
    <div class="form-group">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time, class: 'form-control', placeholder: "When will this task be complete?" %>  <!-- Can this be a calculated field? -->
  </div>
    <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control', placeholder: "Add additional details here" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %> 

app/views/welcome/about.html.erb
<h1>About PartyTable</h1>
<p>Figuring out how to plan a party is just as difficult as actually planning a party. PartyTable is a sophisticated task management system that lets you efficiently plan a party.  
</p>

app/views/welcome/index.html.erb
<div class="jumbotron y text-center">
  <h1>PartyTable</h1>
   <h3>Plan your next dinner party without figuring out how to plan a party.</h3>
   <br>
   <br>
   <p><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-lg' %></p>   
</div>

app/views/welcome/welcome.html.erb
<div class="jumbotron y">
  <h1 class="text-center">Welcome to PartyTable!</h1>
   <h3>My Parties:</h3>
    <% if current_user.parties.any? %>
      <ul>
          <% current_user.parties.each do |party| %>
            <% if party %>
              <li><%= party.name %> - 
                <% if party.date %><%= party.date.strftime("%B %d %Y") %><% end %> 
                <%= link_to "View party", party_path(party) %> | <%= link_to "Timeline Planner", timeline_party_path(party) %>
                <%= link_to party, method: :delete, data: { confirm: "Delete this party?"  } do %><i class="glyphicon glyphicon-remove"> </i>Delete<% end %>
              </li>                
            <% end %>
          <% end %>
      </ul>
   <% else %>
    <p>Don't you think it's time you threw an awesome dinner party?</p>
   <% end %>
  <br>
  <!--    <h3>Past Parties:</h3> // List of past parties goes here
  <br> -->
   <p class="text-center"><%= link_to "Start A New Party", new_party_path, class: 'btn btn-success btn-lg' %></p>   
</div>